import java.util.Random;

class Randomnumber extends Thread {
    int count;
    public Randomnumber(int count) {
        this.count = count;
    }

    public void run() {
        Random random = new Random();
        for (int i = 0; i < count; i++) {  
            int number = random.nextInt(100);
            System.out.println("Number Generated by thread1 is: " + number);

            if (number % 2 == 0) {
                new Square(number).start();
            } else {
                new Cube(number).start();
            }

            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                System.out.println("Thread is interrupted during sleep");
            }
        }
        System.out.println("Random number generation completed.");
    }
}

class Square extends Thread {
    private int number;

    public Square(int number) {
        this.number = number;
    }

    public void run() {
        System.out.println("Square of " + number + " is: " + (number * number));
    }
}

class Cube extends Thread {
    private int number;

    public Cube(int number) {
        this.number = number;
    }

    public void run() {
        System.out.println("Cube of " + number + " is: " + ((number * number) * number));
    }
}

public class practical34 {
    public static void main(String[] args) {
        int numberOfIterations = 10;
        Randomnumber r1 = new Randomnumber(numberOfIterations);
        r1.start();
    }
}
